- name: install and enable Nginx 
  hosts: frontend 
  become: yes 
  tasks:
  - name: install Nginx 
    ansible.builtin.package:
      name: nginx
      state: present 
  - name: start and enable nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes