- name: play level variables 
  hosts: local 
  connection: local 
  vars:
    Name: "Manoj Kumar"
    Profession: "Devops Engineer" 
    Salary: 50000
  tasks:
  - name: printing play level variables 
    ansible.builtin.debug:
      msg: "My name is {{ Name}} My Profession is {{Profession}} My salary is {{ Salary }}"