- name: File Level Variables in Ansible 
  hosts: local 
  connection: local 
  vars_files:
    - info.yaml 
  
  tasks:
    - name: Print User Information
      ansible.builtin.debug:
        msg: "My name is {{ Name }}. Currently i am working as a {{ Profession }}. I am from {{ Hometown }}"