- name: Task level variables 
  hosts: local 
  connection: local
  vars:
    Name: Manoj 
  tasks:
  - name: printing task level variables 
    vars:
      Name: "Manoj Kumar"
    ansible.builtin.debug:
      msg: "My name is {{ Name }}"