- name: printing prompt variables 
  hosts: local 
  connection: local 
  become: yes 
  vars_prompt:
  - name: username 
    prompt: "Please enter your username"
    private: no
  - name: password 
    prompt: "please enter your password"
    private: yes
  tasks:
  - name: printing username and password 
    ansible.builtin.debug:
      msg: "Your username is {{ username }} and password is {{ password }}"