- name: variables from prompt 
  hosts: local  
  connection: local 
  vars_prompt:
  - name: uname 
    prompt: please enter your username
    private: false 
  - name: password 
    prompt: please enter your password
    private: true 
  tasks:
  - name: printing username and password 
    ansible.builtin.debug:
      msg: "your username is {{ uname }} your password is {{ password }}"
