- name: playbook control using ansible_facts 
  hosts: local 
  connection: local 
  become: yes 
  taks:
  - name: install nginx if os family is redhat
    ansible.builtin.dnf:
      name: nginx 
      state: present 
    when: ansible_os_family=="RedHat"
  - name: install nginx if os family is debian 
    ansible.builtin.apt: 
      name: nginx 
      state: present 
    when: ansible_os_family=="Debian" 


