- name: install packages through loop 
  hosts: local 
  connection: local 
  become: yes 
  tasks:
  - name: install packages through loop 
    ansible.builtin.package:
      name: "{{item}}"
      state: present 
    loop:
    - ansible 
    - python3 
    - git 
    - nginx
    - java 
  